name: hierarchicalforecast
channels:
  - conda-forge
dependencies:
  - numpy
  - numba
  - pandas
  - scikit-learn
  - quadprog
  - clarabel
  - matplotlib
  - pip
  - pip:
    - nbdev
    - ipython<=8.32.0