name: hierarchicalforecast
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - numpy
  - numba
  - pandas
  - scikit-learn
  - quadprog
  - clarabel
  - matplotlib
  - tqdm
  - pip
  - pip:
    - nbdev==2.3.25
