# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"bottom_up": "core.ipynb",
         "top_down": "core.ipynb",
         "crossprod": "core.ipynb",
         "min_trace": "core.ipynb",
         "HierarchicalReconciliation": "core.ipynb"}

modules = ["core.py"]

doc_url = "https://Nixtla.github.io/hierarchicalforecast/"

git_url = "https://github.com/Nixtla/hierarchicalforecast/tree/main/"

def custom_doc_links(name): return None
